# IMPORTING THE OS MODULE 
import os 

# USING THE LISTDIR FUNCTION AND PASSING THE DIRECTORY ADDRESS WHILE STORING IT IN VARIABLE
a=os.listdir('/Users')


# PRINTING EACH ELEMENT IN THE DIRECTORY
for dir in a:
    print(dir)